estados = ["Preseleccion","Inscrito","Aprobado"]
riesgo = ["Normal","En Riesgo","Filtrado"]
rutas = ["NodeJS","Java","Netcore"]
camper = []
trainer = []
notas = []
horarios = ["6am-9am","10am-2pm","3pm-5pm","6pm-10pm"]